# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import device_control_pb2 as device__control__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceControlServiceStub:
    """---------------------------------------------------------------------
    СЕРВИС УПРАВЛЕНИЯ
    ---------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCommand = channel.unary_unary(
                '/devicecontrol.DeviceControlService/SendCommand',
                request_serializer=device__control__pb2.CommandRequest.SerializeToString,
                response_deserializer=device__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetDevices = channel.unary_unary(
                '/devicecontrol.DeviceControlService/GetDevices',
                request_serializer=device__control__pb2.GetDeviceRequest.SerializeToString,
                response_deserializer=device__control__pb2.GetDeviceResponse.FromString,
                _registered_method=True)
        self.GetBlockStatus = channel.unary_unary(
                '/devicecontrol.DeviceControlService/GetBlockStatus',
                request_serializer=device__control__pb2.GetBlockStatusRequest.SerializeToString,
                response_deserializer=device__control__pb2.GetBlockStatusResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/devicecontrol.DeviceControlService/SubscribeEvents',
                request_serializer=device__control__pb2.EventSubscribeRequest.SerializeToString,
                response_deserializer=device__control__pb2.DeviceEvent.FromString,
                _registered_method=True)


class DeviceControlServiceServicer:
    """---------------------------------------------------------------------
    СЕРВИС УПРАВЛЕНИЯ
    ---------------------------------------------------------------------

    """

    def SendCommand(self, request, context):
        """Отправка команды устройству
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevices(self, request, context):
        """Получение списка устройств блока
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockStatus(self, request, context):
        """Получение статуса блока
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Подписка на события остановки процессов (server-side streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=device__control__pb2.CommandRequest.FromString,
                    response_serializer=device__control__pb2.CommandResponse.SerializeToString,
            ),
            'GetDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevices,
                    request_deserializer=device__control__pb2.GetDeviceRequest.FromString,
                    response_serializer=device__control__pb2.GetDeviceResponse.SerializeToString,
            ),
            'GetBlockStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockStatus,
                    request_deserializer=device__control__pb2.GetBlockStatusRequest.FromString,
                    response_serializer=device__control__pb2.GetBlockStatusResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=device__control__pb2.EventSubscribeRequest.FromString,
                    response_serializer=device__control__pb2.DeviceEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'devicecontrol.DeviceControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('devicecontrol.DeviceControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceControlService:
    """---------------------------------------------------------------------
    СЕРВИС УПРАВЛЕНИЯ
    ---------------------------------------------------------------------

    """

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devicecontrol.DeviceControlService/SendCommand',
            device__control__pb2.CommandRequest.SerializeToString,
            device__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devicecontrol.DeviceControlService/GetDevices',
            device__control__pb2.GetDeviceRequest.SerializeToString,
            device__control__pb2.GetDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlockStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devicecontrol.DeviceControlService/GetBlockStatus',
            device__control__pb2.GetBlockStatusRequest.SerializeToString,
            device__control__pb2.GetBlockStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/devicecontrol.DeviceControlService/SubscribeEvents',
            device__control__pb2.EventSubscribeRequest.SerializeToString,
            device__control__pb2.DeviceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
